### ISSUE TITLE
Very Odd Result

### ISSUE THREAD

**Issue by htcml** [cbellei/abyes#1]
I ran the following code many times using your aByes library. Sometimes it reports A or B is winner. This is very odd because both has the mean of 0.4 and only runs for 100 data points. Shouldn't the result of "inconclusive" or "effectively equivalent" be expected?

data = [np.random.binomial(1, 0.4, size=100), np.random.binomial(1, 0.4, size=100)]
exp = ab.AbExp(method='analytic', rule='loss', decision_var='lift', toc=0.002, plot=True)
exp.experiment(data)

**Comment by cbellei** [comment]
Hi taihds,
The result is "inconclusive" most of the time, as I would expect, however once in a while you get a "conclusive" result just out of randomness and because the toc value that you have chosen is quite small.

**Comment by htcml** [comment]
Yes, given only 100 data points is collected, "inconclusive" should be "always" expected. Any results other than "inconclusive" would render the algorithm useless in real practice. 

Do you have a rule of thumb in choosing the right toc? I used 0.002 because VWO paper uses it in Example 7.1.

Here is another case which doesn't "always" give "inconclusive" result no matter which toc I set. 

data = [np.random.binomial(1, 0.4, size=100), np.random.binomial(1, 0.45, size=100)]
exp = ab.AbExp(method='analytic', rule='loss', decision_var='lift', toc=0.005, plot=True)
exp.experiment(data)

**Comment by cbellei** [comment]
Using a frequentist terminology, the point is what "type-I error" you are willing to accept for your case. If it is 5%, then you would expect to have 5 conclusive results every 100 tries - even when there is no difference between the two populations. 
In the example above, you are using 0.4 and 0.45 as probability of success - so no wonder you are getting conclusive results rather often...

**Comment by htcml** [comment]
Yes, I agree with your frequentist explanation. However, the VWO paper doesn't discuss anything about the error rate of its approach.

**Comment by htcml** [comment]
I ran the following code:

```
res = []
for i in range(100):
    data = [np.random.binomial(1, 0.4, size=100), np.random.binomial(1, 0.4, size=100)]
    exp = AbExp(method='analytic', rule='loss', decision_var='lift', toc=0.01, plot=False)
    exp.experiment(data)
    res.append(exp.result)
```
Result:
```
Inconclusive: 50
B win: 28
A win: 22

```
This is way more than 5% error rate.

**Comment by cbellei** [comment]
Then you shouldn't use toc=0.01 but a higher value. I am going to close
this issue as I don't see any problems.

**Comment by htcml** [comment]
So what toc value do you suggest? You said toc should be set according to business need in your blog post answer.

**Comment by htcml** [comment]
I set toc = 0.05 and re-ran the test. The result is even worse:

A win: 30
B win: 32
Equal: 38

**Comment by cbellei** [comment]
Apologies, you should be actually decreasing the value of toc. As you decrease it, you will start observing more and more "nan" results that represent an inconclusive result: none of the variants had an expected loss < toc. [The "threshold of caring" represents the value below which it is fine for you to declare the A or B variant to be the winner (depending on which one of them gives you an expected loss < toc).] 

As you decrease toc, it becomes more and more difficult to declare winner any of the variants. On the contrary, as you increase toc both A and B start becoming "winners" so the experiment should start giving conclusive results - roughly the same for A and B in your case. Finally, for really high values of toc you should observe the "equal" result to dominate as A and B are always winners.

**Comment by cbellei** [comment]
Regarding what's the best value for "toc". If you don't care about a difference in the mean between A and B that is smaller than 1% (for example 20% vs. 19% click rate) then you should set toc=0.01. This may be a good starting point, but again it depends on the business. For organizations with a large user base, they may care about a difference in 0.1% so they would set toc=0.001.

**Comment by htcml** [comment]
Thanks for the pointers!
